### PR TITLE
Added option to disable logs output after tests

### PR DESCRIPTION
**Pull request by plyul**

### CODE REVIEW

**Comment by todofixthis** [comment]
Hi @plyul thanks for proposing this change!

Out of curiosity, what is your use case for this functionality?

**Comment by plyul** [comment]
Hi, @todofixthis 
I write integration tests for an application.
To ensure the application works as intended, test cases analyse not only app response, but also app logs.
To gain necessary info in logs app is started with log level DEBUG resulting in a lot of logs.
This is what i need for testing routines, but i don't need all this debug info in final pytest output.
I believe described scenario (or something like that) is not unique to me therefore this change was proposed.

**Comment by todofixthis** [comment]
Thanks @plyul that makes sense.  I wonder if maybe we should disable container logs by default unless the `--verbose` flag is passed.  @RmStorm what do you think?

**Comment by RmStorm** [comment]
> Thanks @plyul that makes sense. I wonder if maybe we should disable container logs by default unless the `--verbose` flag is passed. @RmStorm what do you think?

Yes now that I think about it suppressing the logs should actually be default behaviour.

**Comment by RmStorm** [comment]
Log suppression is available in 3.1.0 and published on pypi

**Pull request merged**
